---
- name: clone latest opus
  git: repo=git://git.opus-codec.org/opus.git
       dest={{ ffmpeg_source_dir }}/opus
       accept_hostkey=yes
       version={{ ffmpeg_opus_version }}
       
- name: compile libopus
  command: "{{ item }}" 
  args:
    chdir: "{{ ffmpeg_source_dir }}/opus" 
    creates: "{{ ffmpeg_lib_dir }}/libopus.a"
  with_items:
    - ./autogen.sh
    - ./configure --disable-shared
    - make {{ ffmpeg_cpu_flag }}
    - make install
    - make distclean       