- name: clone latest x264
  git: repo=git://git.videolan.org/x264.git
       dest={{ ffmpeg_source_dir }}/x264
       accept_hostkey=yes
       version={{ ffmpeg_x264_version }}

- name: compile x264
  command: "{{ item }}" 
  args:
    chdir: "{{ ffmpeg_source_dir }}/x264" 
    creates: "{{ ffmpeg_bin_dir }}/x264"
  with_items:
    - ./configure --bindir={{ ffmpeg_bin_dir }} --enable-static
    - make {{ ffmpeg_cpu_flag }}
    - make install
    - make distclean